# Examen A Módulo 1 - Optimización.

**Lea cuidadosamente las siguientes indicaciones antes de comenzar el examen:**
- Para resolver el examen edite este mismo archivo y renómbrelo de la siguiente manera: *Examen1_ApellidoNombre*, donde *ApellidoNombre* corresponde a su apellido paterno con la inicial en mayúscula, seguido de su primer nombre con la inicial en mayúscula **sin tildes**. Por ejemplo, en mi caso el nombre del archivo sería *Examen1_MoralesGabriel*.
- Resuelva los puntos en el espacio provisto. Si requiere agregar más celdas para código o escritura, hágalo (`Esc`,`B`) o (`Esc`,`A`).
- Recuerde que también se está evaluando su capacidad de interpretar los resultados. Escriba sus interpretaciones/conclusiones en celdas utilizando *Markdown*.
- El formato de presentación de todo el examen en general debe ser adecuado. Use tamaños de letra, colores, etiquetas, etcétera.
- No se resuelven dudas de ningún tipo por los profesores de la asignatura. Por favor, absténgase de preguntar.
- Revise bien el tipo de examen. Sólo se le calificará si realiza el tipo de examen asignado.

## 1. Optimización de funciones con `Sympy`

Funciones permitidas: subs, solve, var, expresiones matemáticas


Un cine cobra 86 pesos la entrada estándar y 60 pesos la entrada a estudiantes. Una sala con capacidad para 120 personas se ocupó al 70\%. Los ingresos para esa función fueron de 6,600 MXN. ¿Cuántos estudiantes entraron?

Variables:

x---normal

y--- estudiantes

Restricciones: 

Solo entro el 70%

$x+y=(120*.7)$

Se vendieron 6600

$86x+60y=6600$



In [190]:
import sympy as sp
sp.var("x")
sp.var("y")

eq1= x+y-(120*.7)
eq2= (86*x)+(60*y)-6600

x_eq1=sp.solve(eq1, x)[0]
y_eq2=eq2.subs(x, x_eq1)
y_sol=sp.solve(y_eq2, y)[0]
x_sol=x_eq1.subs(y, y_sol)



624.0 - 26*y

Fueron 24 estudiantes. 

El cine ofrece combos y opciones individuales. El combo 'amigos' tiene un costo de 156 MXN y consiste de 2 refrescos y unas palomitas. Existe también el combo 'nachos' que tiene un costo de 112 MXN y consiste de un refresco y una orden de nachos. Por separado el refresco tiene un costo de 60 MXN, las palomitas 58 MXN y los nachos 72 MXN. Se obtuvo un total de 6450 de ingresos en dulcería:

- 38 combos vendidos
- 70 refrescos vendidos
- 33 órdenes de palomitas grandes vendidas
- 16 órdenes de nachos vendidas

¿Cuántas personas compraron palomitas sueltas?

Restricciones: 

Combo amigos $x+2y=156$

Combo nachos $y+z=122$

Costo separado: 

x=58
y=60
z=72

Ventas: 

- 38 combos vendidos
- 70 refrescos vendidos
- 33 órdenes de palomitas grandes vendidas
- 16 órdenes de nachos vendidas

Unión de variables: 

Ventas
Refrescos

$2ca+cn+y=70$

Nachos

$cn+z=16$

Palomitas

$ca+x=33$

Combos venididos

c$ca+cn=38$

Ganancia total

$156ca+112cn+58x+60y+72z=6450$


In [307]:
import sympy as sp
sp.var("x")
sp.var("y")
sp.var("z")
sp.var("ca")
sp.var("cn")


eq1=2*ca+cn+y-70
eq2=cn+z-16
aq3=ca+x-33
eq4=ca+cn-38
eq5=156*ca+112*cn+58*x+60*y+72*z-6450

eq1_y=sp.solve(eq1, y)[0]#y=
eq2_z=sp.solve(eq2, z)[0]#z=
eq3_ca=sp.solve(eq3, ca)[0] #ca= importante
eq1_n=eq1_y.subs(ca, eq3_ca)#y= nueva
eq4_cn=sp.solve(eq4, cn)[0]#cn= importante
eq4_n=eq4_cn.subs(ca, eq3_ca)#cn pero con x
eq1_n2=eq1_n.subs(cn, eq4_n)#y= nueva sin ca y cn importante
eq1_n2


x - 1

In [308]:
eq3_ca

33 - x

In [311]:
eq4_n

x + 5

In [323]:
eq2_n=eq2_z.subs(cn, eq4_n) #z=
eq2_n

11 - x

In [325]:
eq5_n=eq5.subs(y, eq1_n2).subs(z, eq2_n).subs(cn, eq4_n).subs(ca, eq3_ca)
eq5_n

2*x - 10

In [327]:
sp.solve(eq5_n, x)[0]


5

La cantidad de palomitas individuales vendidas fueron 5. 

## 2. Programación lineal

Una empresa produce costales de 3 tipos de fertilizantes para diferentes aplicaciones utilizando cuantro componentes químicos: azufre, potasio, fósforo y nitrógeno. La información de cada tonelada de fertilizante es:


<table>
  <tr>
      <th>Fertilizante</th>
      <th>Fósforo</th>
      <th>Azufre</th>
      <th>Potasio</th>
      <th>Nitrógeno</th>
      <th>Precio de venta </th>
  </tr>
  <tr>
      <td>A</td>
      <td>3 kg</td>
      <td>5 kg</td>
      <td>4 kg</td>
      <td>2 kg </td>
      <td>\$40000</td>
  </tr>
  <tr>
      <td>B</td>
      <td>4 kg</td>
      <td>3 kg</td>
      <td>2 kg</td>
      <td>1 kg</td>
      <td>\$50000</td>
  </tr>
  <tr>
      <td>C</td>
      <td>5 kg</td>
      <td>2 kg</td>
      <td>3 kg</td>
      <td>4 kg</td>
      <td>\$60000</td>
  </tr>

</table>

La máquina que se usa para mezclar el fertilizante C necesita mantenimiento y por lo tanto sólo puede mezclar 10 toneladas. Además, hay un pedido de 8 toneladas del fertilizante A.

Dado que en almacén se tienen 90 kg de fósforo, 120 kg de nitrógeno, 80 kg de azufre y 95 kg de potasio, ¿cuánto recomiendas que se mezcle de cada fertilizante? (Nota: No se permiten fracciones de toneladas)

Criterio: maximizar

Variables

Fertizante A--- A

Fertilizante B---B

Fertilizante C---C

Función:

C= 40000A+50000B+60000C

1*3

3*n

Restricciones:

Fosforo

$3A+4B+5C\leq90$

Azufre:

$5A+3B+2C\leq80$

Potasio:

$4A+2B+3C\leq95$

Nitrogeno:

$2A+1B+4C\leq120$


Falla

$C\leq10$

Pedido

$A\leq-8$

In [114]:
import numpy as np
import scipy.optimize as opt

C=np.array([-40000,
             -50000,
             -60000])

Aub=np.array([[3, 4, 5],
             [5, 3, 2],
              [4, 2, 3],
              [2, 1, 4],
              [0, 0, 1],
              [-1, 0, 0]])

bub=np.array([90,
              80,
              95,
              120,
              10,
              -8])
sol=opt.linprog(C, Aub, bub,  integrality=1)


In [116]:
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -1130000.0
              x: [ 8.000e+00  9.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 8.000e+00  9.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  2.700e+01  7.100e+01
                              4.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -1130000.0
        mip_gap: 0.0

¿Cuál es el ingreso total?

In [118]:
sol.fun*-1

1130000.0

El ingreso total es de 1130000$

¿Cuánto fósforo quedó en almacén?

In [120]:
(sol.x[0]*3)+(sol.x[1]*4)+(sol.x[2]*5)-90


0.0

Dado que la produccion de Fosfroro se llevo 90kg se puede decir que la cantidad que sobro de fosforo fue de 0

## 3. Regresión lineal

Se quiere predecir la resistencia a la compresión de concreto en función de las proporciones de los componentes en la mezcla (cemento, arena, agua, agregado). La constructora que está realizando el análisis tiene datos históricos donde se registraron cantidades de materia y la resistencia medida:

In [11]:
import pandas as pd
data = {
    'Cemento (kg)': [350, 400, 300, 450, 380, 410, 320, 370, 390, 360,
                     340, 430, 315, 405, 425, 345, 395, 355, 440, 310,
                     385, 370, 425, 335],
    'Arena (kg)': [600, 550, 700, 500, 580, 540, 650, 590, 570, 610,
                   630, 520, 660, 545, 530, 620, 560, 605, 515, 670,
                   575, 590, 535, 625],
    'Agua (kg)': [180, 160, 200, 170, 175, 165, 185, 172, 170, 190,
                  182, 165, 195, 175, 168, 180, 175, 185, 162, 198,
                  178, 172, 170, 180],
    'Agregado (kg)': [1000, 1100, 950, 1200, 1050, 1150, 980, 1020, 1080, 970,
                      990, 1120, 950, 1060, 1140, 990, 1040, 1010, 1160, 940,
                      1070, 1030, 1110, 1025],
    'Resistencia a la compresión (MPa)': [35, 42, 30, 50, 38, 44, 32, 36, 40, 34,
                                          33, 48, 31, 43, 47, 37, 41, 35, 49, 29,
                                          39, 36, 45, 33]
}
data = pd.DataFrame(data)
data

Cemento (kg)  Arena (kg)  Agua (kg)  Agregado (kg)  \
0            350         600        180           1000   
1            400         550        160           1100   
2            300         700        200            950   
3            450         500        170           1200   
4            380         580        175           1050   
5            410         540        165           1150   
6            320         650        185            980   
7            370         590        172           1020   
8            390         570        170           1080   
9            360         610        190            970   
10           340         630        182            990   
11           430         520        165           1120   
12           315         660        195            950   
13           405         545        175           1060   
14           425         530        168           1140   
15           345         620        180            990   
16           395         560        175           1040   
17           355         605        185           1010   
18           440         515        162           1160   
19           310         670        198            940   
20           385         575        178           1070   
21           370         590        172           1030   
22           425         535        170           1110   
23           335         625        180           1025   

    Resistencia a la compresión (MPa)  
0                                  35  
1                                  42  
2                                  30  
3                                  50  
4                                  38  
5                                  44  
6                                  32  
7                                  36  
8                                  40  
9                                  34  
10                                 33  
11                                 48  
12                                 31  
13                                 43  
14                                 47  
15                                 37  
16                                 41  
17                                 35  
18                                 49  
19                                 29  
20                                 39  
21                                 36  
22                                 45  
23                                 33

Ajusta un modelo utilizando mínimos **cuadrados** para encontrar una función que pueda predecir la resistencia del concreto.

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt


In [74]:
y=data['Resistencia a la compresión (MPa)']
x1=data['Cemento (kg)']
x2=data['Arena (kg)']
x3=data['Agua (kg)']
x4=data['Agregado (kg)']

In [75]:
n=len(y)
ones=np.ones([n,1])
xf1=np.reshape(x1,(n,1))
xf2=np.reshape(x2,(n,1))
xf3=np.reshape(x3,(n,1))
xf4=np.reshape(x4,(n,1))
X=np.hstack((ones, xf1, xf2, xf3, xf4))
X

array([[1.000e+00, 3.500e+02, 6.000e+02, 1.800e+02, 1.000e+03],
       [1.000e+00, 4.000e+02, 5.500e+02, 1.600e+02, 1.100e+03],
       [1.000e+00, 3.000e+02, 7.000e+02, 2.000e+02, 9.500e+02],
       [1.000e+00, 4.500e+02, 5.000e+02, 1.700e+02, 1.200e+03],
       [1.000e+00, 3.800e+02, 5.800e+02, 1.750e+02, 1.050e+03],
       [1.000e+00, 4.100e+02, 5.400e+02, 1.650e+02, 1.150e+03],
       [1.000e+00, 3.200e+02, 6.500e+02, 1.850e+02, 9.800e+02],
       [1.000e+00, 3.700e+02, 5.900e+02, 1.720e+02, 1.020e+03],
       [1.000e+00, 3.900e+02, 5.700e+02, 1.700e+02, 1.080e+03],
       [1.000e+00, 3.600e+02, 6.100e+02, 1.900e+02, 9.700e+02],
       [1.000e+00, 3.400e+02, 6.300e+02, 1.820e+02, 9.900e+02],
       [1.000e+00, 4.300e+02, 5.200e+02, 1.650e+02, 1.120e+03],
       [1.000e+00, 3.150e+02, 6.600e+02, 1.950e+02, 9.500e+02],
       [1.000e+00, 4.050e+02, 5.450e+02, 1.750e+02, 1.060e+03],
       [1.000e+00, 4.250e+02, 5.300e+02, 1.680e+02, 1.140e+03],
       [1.000e+00, 3.450e+02, 6.200e+02,

In [78]:
y_vector=np.reshape(y,(n,1))
y_vector

array([[35],
       [42],
       [30],
       [50],
       [38],
       [44],
       [32],
       [36],
       [40],
       [34],
       [33],
       [48],
       [31],
       [43],
       [47],
       [37],
       [41],
       [35],
       [49],
       [29],
       [39],
       [36],
       [45],
       [33]], dtype=int64)

In [88]:
n,p=X.shape
beta=np.random.randn(p)

def funcion(beta,X, y):
  beta=np.reshape(beta, [p, 1])
  y_pred=X@beta
  error=y_pred-y
  rss=error.T@error
  return rss
rss=opt.minimize(funcion, beta, args=(X, y_vector))
rss

  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 29.849891667523114
        x: [-5.576e+01  1.374e-01  2.436e-02  1.949e-02  2.397e-02]
      nit: 10
      jac: [-2.384e-07 -2.861e-06  1.240e-05 -9.537e-07  3.386e-05]
 hess_inv: [[ 2.554e-04 -1.084e-04 ...  3.194e-04  3.982e-05]
            [-1.084e-04  2.493e-04 ... -2.600e-04 -1.058e-04]
            ...
            [ 3.194e-04 -2.600e-04 ...  1.141e-03  7.853e-05]
            [ 3.982e-05 -1.058e-04 ...  7.853e-05  4.686e-05]]
     nfev: 324
     njev: 52

¿Qué efecto tiene cada factor en la resistencia de la mezcla?

Indifcan cuanto se debe de agregar para que la resitencia se optima entre las variables que se consideran en este caso la resistencia a la compresión sería de 24.62(MPA)

¿Cuál será la resistencia si mezclo 390 kg de cemento, 570 kg de arena, 170 kg de agua y 1080 kg de agregado?

In [125]:
((rss.x[1]*390)+(rss.x[2]*570)+(rss.x[3]*170)+(rss.x[4]*1080)+rss.x[0])

40.905725692982585

La resistencia de la mezcla es de 40.90 MPa

## 4. Regresión logística

Un equipo de ingenieros quiere saber si una muestra de concreto hidráulico fallará o no bajo determinadas condiciones, basándose en experiencias pasadas.

<table>
  <thead>
    <tr>
      <th>Resistencia a la compresión (MPa)</th>
      <th>Edad del concreto (días)</th>
      <th>Relación agua-cemento</th>
      <th>Falla (Sí/No)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>25</td>
      <td>28</td>
      <td>0.45</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>40</td>
      <td>56</td>
      <td>0.35</td>
      <td>No</td>
    </tr>
    <tr>
      <td>30</td>
      <td>28</td>
      <td>0.50</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>50</td>
      <td>90</td>
      <td>0.30</td>
      <td>No</td>
    </tr>
    <tr>
      <td>35</td>
      <td>28</td>
      <td>0.40</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>55</td>
      <td>120</td>
      <td>0.32</td>
      <td>No</td>
    </tr>
    <tr>
      <td>45</td>
      <td>60</td>
      <td>0.36</td>
      <td>No</td>
    </tr>
    <tr>
      <td>20</td>
      <td>7</td>
      <td>0.55</td>
      <td>Sí</td>
    </tr>
  </tbody>
</table>


Sí 1 No 0

1. ¿Qué factor afecta más? (Utiliza un vector de ceros como tu beta inicial)

In [49]:
R=[25, 40, 30, 50, 35, 55, 45, 20]
E=[28, 56, 28, 90, 28, 120, 60, 7]
REL=[.45, .35, .50, .30, .40, .32, .36, .55]
F=[1, 0, 1, 0, 1, 0, 0, 1]


In [50]:
n=len(F)
ones=np.ones([n, 1])
BR=np.reshape(R, (n, 1))
BE=np.reshape(E, (n, 1))
BRL=np.reshape(REL, (n, 1))
ones, BR, BE, BRL


(array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]),
 array([[25],
        [40],
        [30],
        [50],
        [35],
        [55],
        [45],
        [20]]),
 array([[ 28],
        [ 56],
        [ 28],
        [ 90],
        [ 28],
        [120],
        [ 60],
        [  7]]),
 array([[0.45],
        [0.35],
        [0.5 ],
        [0.3 ],
        [0.4 ],
        [0.32],
        [0.36],
        [0.55]]))

In [51]:
X=np.hstack((ones, BR, BE, BRL))
X

array([[  1.  ,  25.  ,  28.  ,   0.45],
       [  1.  ,  40.  ,  56.  ,   0.35],
       [  1.  ,  30.  ,  28.  ,   0.5 ],
       [  1.  ,  50.  ,  90.  ,   0.3 ],
       [  1.  ,  35.  ,  28.  ,   0.4 ],
       [  1.  ,  55.  , 120.  ,   0.32],
       [  1.  ,  45.  ,  60.  ,   0.36],
       [  1.  ,  20.  ,   7.  ,   0.55]])

In [52]:
y_vector=np.reshape(F,(n, 1))
y_vector

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [53]:
def pred(beta, X):
  return 1/(1+np.exp(-X@beta))

In [54]:
def J(beta, X, y):
  epsilon=1e-100
  n, p=X.shape
  beta=np.reshape(beta, [p, 1])
  y_pred=pred(beta, X)
  e=y*np.log(y_pred+epsilon)+(1-y)*np.log(1-y_pred+epsilon)
  return-np.sum(e)

beta=[0, 0, 0, 0]
rrs=opt.minimize(J, beta, args=(X, y_vector))
rrs


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.1236079788292108e-07
        x: [ 2.223e+01  2.043e+00 -2.254e+00  1.432e+01]
      nit: 28
      jac: [ 9.686e-08  5.215e-06  7.354e-06  4.470e-08]
 hess_inv: [[ 3.268e+06  2.756e+05 -3.119e+05  2.104e+06]
            [ 2.756e+05  2.324e+04 -2.630e+04  1.775e+05]
            [-3.119e+05 -2.630e+04  2.977e+04 -2.009e+05]
            [ 2.104e+06  1.775e+05 -2.009e+05  1.355e+06]]
     nfev: 155
     njev: 31

Si nos vamos por los signos el factor que afectaría más seria el la edad del concreto, sin embargo, si nos vamos por magnitud sería la relación agua cemento.

2. Calcula la probabilidad de falla para una muestra con las siguientes características:
- Resistencia a la compresión: 38 MPa
- Edad del concreto: 30 días
- Relación agua-cemento: 0.40

In [130]:
((rss.x[1]*38)+(rss.x[2]*30)+(rss.x[3]*.4)+rss.x[0])



-49.799747046551644

La probabilidad de falla con las caracteristicas presentadas es de 49%